-- Kiểm tra cấu trúc bảng SalesOrders
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SalesOrders'
ORDER BY ORDINAL_POSITION;
